version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seas11
      POSTGRES_DB: frello
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:seas11@db:5432/frello

  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - server

volumes:
  pgdata:
