version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seas11
      POSTGRES_DB: frello
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:seas11@db:5432/frello
      OPENAI_KEY: ${OPENAI_KEY}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      DOMAIN_BASE: ${DOMAIN_BASE}
      PORT: ${PORT}
    env_file:
      - .env

  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - server

volumes:
  pgdata:
